### PR TITLE
fix issue #8

### LINKED ISSUE #8: on branch code-rework-and-features: Bomb exploaded with an error
Got his error after clicking on unrevealed bomb:
Image
Dont really know how to reproduce this error

### PR DESCRIPTION
**Pull request by KursonOfficial**
closes #8

### CODE REVIEW

File: field.lua [hunk 1]
```diff
@@ -105,7 +99,7 @@ function Cell.new(x, y, isBomb)
 	self = {}
 	self.mines = 0
 	self.bomb = isBomb
-	if isBomb then self.bombImage = math.random(0 , #sprite.bombs.quad + 1) end
+	if isBomb then self.bombImage = math.random(0 , #sprite.bombs.quad) end
 	self.revealed = false
 	Cells[x][y] = self
 end
```
Comment (Cadragonit) [inline field.lua]: Nice solution btw

File: field.lua [hunk 2]
```diff
@@ -140,7 +134,7 @@ function Field.draw()
 				RTCorX, RTCorY = math.floor( RTCorX / Cell.cellSize) , math.floor( RTCorY / Cell.cellSize)
 				LBCorX, LBCorY = math.floor( LBCorX / Cell.cellSize) , math.floor( LBCorY / Cell.cellSize)
 				if Field.zoom > 0.2 then
-					for x  = RTCorX, LBCorX do
+					for x = RTCorX, LBCorX do
 						for y = RTCorY, LBCorY do
```
Comment (Cadragonit) [inline field.lua]: Important change ;3

File: field.lua [hunk 3]
```diff
@@ -168,10 +162,10 @@ function Field.draw()
 								
 								lg.setColor(1, 1, 1)
 								if Cells[x][y].bomb then 
-									lg.draw(sprite.bombs.image, sprite.bombs.quad[Cells[x][y].bombImage],  x * Cell.cellSize + Cell.rCorner/2, y * Cell.cellSize + Cell.rCorner/2, 0, sprite.bombs.scaleFactor - Cell.rCorner/200)
+									lg.draw(sprite.bombs.image, sprite.bombs.quad[Cells[x][y].bombImage], x * Cell.cellSize + Cell.rCorner/2, y * Cell.cellSize + Cell.rCorner/2, 0, sprite.bombs.scaleFactor - Cell.rCorner/200)
 								else
 									if Cells[x][y].mines ~= 0 then
-										lg.draw(sprite.numbers.image, sprite.numbers.quad[Cells[x][y].mines],  x * Cell.cellSize + Cell.rCorner/2, y * Cell.cellSize + Cell.rCorner/2, 0, sprite.numbers.scaleFactor - Cell.rCorner/100)
+										lg.draw(sprite.numbers.image, sprite.numbers.quad[Cells[x][y].mines], x * Cell.cellSize + Cell.rCorner/2, y * Cell.cellSize + Cell.rCorner/2, 0, sprite.numbers.scaleFactor - Cell.rCorner/100)
 									end
```
Comment (Cadragonit) [inline field.lua]: Yeeeee!!! Destroy these spaces!
